#!/usr/bin/env bash

if
  [[ -s "/home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/environment" ]]
then
  source "/home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/environment"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/gems/ruby-2.1.1@rails4.1.0/environment'" >&2
  exit 1
fi
